name: Cowsay UI/MOBILE 2

on: pull_request

jobs:
  Ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: echo
        run: ./script.sh
